version: "3.9"
services:
  backend:
    container_name: dottie-backend
    build: ./backend/
    networks:
      - dottie-network
    ports:
      - "5000:5000"
    volumes:
      - dottie-data:/tmp/data
  frontend:
    container_name: dottie-frontend
    build: ./frontend/
    networks:
      - dottie-network
    ports:
      - "3000:3000"

volumes:
  dottie-data:

networks:
  dottie-network: